### ISSUE TITLE
Wrong reshape

### ISSUE THREAD

**Issue by Itsukara** [ageron/tf2_course#10]
```reshape(-1, 1)``` in following code looks wrong [01_neural_nets_with_keras.ipynb Exercise 3 – Solution 3.1)]. I think ```reshape(-1, 28*28)``` is correct code. Could you confirm it?
```
X_train_scaled = scaler.fit_transform(X_train.astype(np.float32).reshape(-1, 1)).reshape(-1, 28, 28)
X_valid_scaled = scaler.transform(X_valid.astype(np.float32).reshape(-1, 1)).reshape(-1, 28, 28)
X_test_scaled = scaler.transform(X_test.astype(np.float32).reshape(-1, 1)).reshape(-1, 28, 28)
```

**Comment by ageron** [comment]
Hi @Itsukara ,

Thanks for your feedback. `X_train` is a 3D array of shape [55000, 28, 28]. Unfortunately, Scikit-Learn's `StandardScaler` expects a 2D array as input, so to use it we must first reshape `X_train` to a 2 array of shape [55000, 784] where each image is flattened to a long list of 28*28=784 pixel values: we do this using ~`.reshape(-1, 1)`~ **edit: this should have been `.reshape(-1, 28 * 28)`**. Then once the scaler has standardized every pixel (based on the mean and standard deviation of all the pixels at that location across the training set), it returns a 2D array of the same shape [55000, 784] that we need to convert back to the original shape, hence the final `.reshape(-1, 28, 28)`.
Hope this helps.

**Comment by ageron** [comment]
I wish the `StandardScaler` accepted arrays of any shape. But the nice thing is Scikit-Learn is easy to extend. Let's define our own `MoreTolerantStandardScaler` and use it to scale the Fashion MNIST dataset. Notice that we don't need to do any reshaping anymore:

```python
import numpy as np
from tensorflow import keras
from sklearn.base import BaseEstimator, TransformerMixin

class MoreTolerantStandardScaler(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        self.mean_ = X.mean(axis=0, keepdims=True)
        self.scale_ = X.mean(axis=0, keepdims=True)
        epsilon = 1e-9
        self.scale_ = np.where(self.scale_==0., epsilon, self.scale_)
        return self
    def transform(self, X, y=None):
        return (X - self.mean_) / self.scale_

fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()
X_valid, X_train = X_train_full[:5000], X_train_full[5000:]
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

scaler = MoreTolerantStandardScaler()
X_train_scaled = scaler.fit_transform(X_train.astype(np.float32))
X_valid_scaled = scaler.transform(X_valid.astype(np.float32))
X_test_scaled = scaler.transform(X_test.astype(np.float32))
```

**Comment by ageron** [comment]
Please close the issue if everything makes sense. :)

**Comment by Itsukara** [comment]
Thank you for very detailed explanation and additional code for enhancement of sklearn StandardScaler.
But I'm afraid that the value of X_train_scaled[0][0] is different in two code: 

![Screenshot from 2019-04-17 23-28-09](https://user-images.githubusercontent.com/17507064/56296074-c28ca100-6168-11e9-92ca-70a8dfe3ba40.png)

**Comment by ageron** [comment]
Ooooops, you are absolutely right! I misread your first comment: you wrote `reshape(-1, 28*28)`, but I thought you wrote `reshape(-1, 28, 28)`. You are right, this is an error, my apologies, I'll fix this right now.

**Comment by Itsukara** [comment]
I'm very lucky to contribute to your great work. Thank you for confirmation.

**Comment by ageron** [comment]
Just fixed! Thanks a lot for this great catch. 👍
