### ISSUE TITLE
Remaining chapters

### ISSUE THREAD

**Issue by dleacock** [ageron/tf2_course#15]
Will the remaining chapters be updated to tensorflow 2.0?

The Chapter 18 Reinforcement learning notebook [here](https://github.com/ageron/handson-ml/blob/master/16_reinforcement_learning.ipynb) is out of date for tensorflow 2.0

**Comment by ageron** [comment]
Hi @dleacock ,
Thanks for your question. You're looking at the notebooks for the 1st edition of my book. The 2nd edition was released in Q4 2019 and it is based on TF 2.x. The notebooks for the 2nd edition are available at: https://github.com/ageron/handson-ml2. The RL notebook is here: https://github.com/ageron/handson-ml2/blob/master/18_reinforcement_learning.ipynb
It also introduces TF Agents.
Hope this helps!
