### ISSUE TITLE
tensorflow=2.0.0 not in conda-forge, or any other channel

### ISSUE THREAD

**Issue by vv111y** [ageron/tf2_course#2]
Tried it out just now. 
channels in my .condarc:

- intel
- pytorch
- anaconda-fusion
- conda-forge
- defaults

ADD: couldn't find it via pip either

**Comment by ageron** [comment]
Hi @vv111y ,

Thanks for your feedback.  Check out the installation instructions in README.me: I mention that conda does not have the 2.0-preview release yet, but using pip should work:

`pip3 install -U -r requirements.txt`

If you only want to install TensorFlow, here is the command:

`pip3 install --upgrade tf-nightly-2.0-preview`

Or if you want the GPU version:

`pip3 install --upgrade tf-nightly-gpu-2.0-preview`

Hope this helps,
Aurélien

**Comment by vv111y** [comment]
Skimmed too quick. With some futzing got it working. Thanks

**Comment by cdataminer** [comment]
vv11y
can you provide some inside as to how you got the tensorflow 2 working on anaconda?
thank you

**Comment by kettenfett** [comment]
> 
> 
> vv11y
> can you provide some inside as to how you got the tensorflow 2 working on anaconda?


create a new env with python 3.6
then just install `tf-nightly-2.0-preview` using `pip`. Simple as that. Note there is no `pip3` in conda, so use `pip` instead.

**Comment by cdataminer** [comment]
thank you..that works..

**Comment by Khoa-NT** [comment]
you can follow this [guide](https://medium.com/@shaolinkhoa/install-tensorflow-gpu-2-0-alpha-on-anaconda-for-windows-10-ubuntu-ced099010b21?fbclid=IwAR1n3qGGmuG_b2Dns3SnnSmmcFYfooLdm292ZpvGJZ9fgwRUzwDxZVU5pak) to install tensorflow 2 on anaconda.

**Comment by pfrumau** [comment]
for me solution was first building the environment using conda-forge as channel with yml file, then updating tensorflow within activated environment with `pip install --upgrade tensorflow`

environment.yml
```
name: tf
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - opencv
  - tensorflow
```

**Comment by mcmar** [comment]
Update for posterity and because this is linked from Google:
conda-forge still doesn't have tensorflow 2 despite being released a long long time ago. Need to install tf2 from "anaconda" channel.

CLI example:
```
conda install -c anaconda tensorflow
```
or
environment.yml example:
```yaml
name: tf2
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - opencv
  - tensorflow
```
