### ISSUE TITLE
`plt.set_ylim` doesn't exist

### ISSUE THREAD

**Issue by darthdeus** [ageron/tf2_course#7]
A little further down in 1.6 it says

> 1.6) Try running pd.DataFrame(history.history).plot() to plot the learning curves. To make the graph more readable, you can also set figsize=(8, 5), call plt.grid(True) and plt.set_ylim(0, 1).

However, `plt.set_ylim(0, 1)` doesn't exist in the version of matplotlib specified in `requirements.txt`. According to the docs it probably needs to be called on the ax object, so something like

```
pd.DataFrame(history.history).plot(figsize=(8, 5)).set_ylim(0, 1)
plt.grid(True)
```

**Comment by ageron** [comment]
Good catch, thanks a lot @darthdeus . The text was incorrect, but the solution was good: `plt.gca().set_ylim(0, 1)`.  I'll fix the text now.
