### ISSUE TITLE
[Bug] Use of X_valid & X_test

### ISSUE THREAD

**Issue by kettenfett** [ageron/tf2_course#9]
Why is X_test used with `model.fit` in excercise 5 of **01_neural_nets_with_keras.ipynb**,  when in all other excersices in that notebook, it's always X_valid? I think X_test is to be reserved for final evaluation only, right? So I think this is a mistake?

**Comment by ageron** [comment]
Great catch, thanks a lot @philippHRO, I just fixed this.
